language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit --coverage-text
